- name: slux_exam
  gather_facts: false
  hosts: [all]
  become: yes

  tasks:
   - name: "Update"
     command: apt -y update
   - name: "Upgrade"
      command: apt -y upgrade
   - name: "Install Python"
      command: apt -y install python3-pip   
   - name: "Install Docker"
      command: pip3 install docker-py
   - name: "Update"
      command: apt -y update
   - name: "Install" 
      command: apt -y install apt-transport-https
   - name: ca-certificates 
      command: apt -y install ca-certificates 
   - name: Curl
      command: apt -y install curl 
   - name: gnupg 
      command: apt -y install gnupg 
   - name: lsb-release
      command: apt -y install lsb-release
   - name: Key
      apt_key: url=https://download.docker.com/linux/ubuntu/gpg
   - name: Add Docker APT repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/{{ ansible_system | lower }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable
   - name: Install Docker
      command: apt-get -y install docker-ce docker-ce-cli containerd.io
   - name: Install docker-compose
      pip:
        name: docker-compose
   - name: Start Docker service
     service:
       name: docker
       state: started
       enabled: yes
       become: yes

    - name: Add user ec2-user to docker group
      user:
        name: ec2-user
        groups: docker
        append: yes
      become: yes

