name: 'MySQL'

on:
  workflow_run:
    workflows:
      - Ansible
    types: 
      - completed
    branches:
      - main
    
jobs:
  mysql:
    name: 'MySQL'
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: terraform.yml
          workflow_conclusion: success
          name: terraform

      - shell: bash
        run: |
          db=$(cat terraform.log | grep -w rds_endpoint)
          db=$(grep "rds_endpoint" terraform.log | awk -F  ":" '{print $1}' )
          db=${db//'rds_endpoint = "'}
          echo $db
          mysql --host $db --port 3306 -uexam_rds -pexam_rds exam_rds < mysql/exam_db.sql